<a href="https://colab.research.google.com/github/rzqynptr/Matematika-Diskrit-24083010042-Amelia/blob/main/24083010042_Amelia_Rizqyna_Putri_Matdis_A_Tugas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from numpy.linalg import norm

# 1. Baca data Excel
file_path = "Data Matdis A.xlsx"
df = pd.read_excel(file_path)

# 2. Ambil kolom C–F sebagai kriteria
C = df.iloc[:, 2:6]

# --- Perbaikan data ---
# Isi NaN dengan mean per kolom
C = C.fillna(C.mean())

# Hapus kolom konstan (supaya korelasi tidak NaN)
C = C.loc[:, C.nunique() > 1]

# Simpan kembali ke dataframe bersih
df_clean = df.copy()
df_clean[C.columns] = C

# Ubah ke numpy array
C = C.to_numpy()

# 3. Tentukan bobot prioritas (matrix P)
P = np.array([0.2, 0.3, 0.4, 0.4])
P = P[:C.shape[1]]   # sesuaikan dengan jumlah kolom C

# 4. Hitung skor total (C × P)
scores = C @ P
df_clean["Skor_Total"] = scores

# Ambil 4 mahasiswa terbaik
top4 = df_clean.nlargest(4, "Skor_Total")

print("Empat mahasiswa terbaik berdasarkan skor total:")
print(top4[["NAMA", "Skor_Total"]])

# 5. Matriks kovarians & korelasi antar kriteria
cov_mat = np.cov(C, rowvar=False)
corr_mat = np.corrcoef(C, rowvar=False)

print("\nMatriks Kovarians:")
print(cov_mat)

print("\nMatriks Korelasi:")
print(corr_mat)

# 6. Cosine similarity antar mahasiswa (handle pembagian 0)
norms = norm(C, axis=1)
norms[norms == 0] = 1e-10   # cegah pembagian 0
cosine_sim = (C @ C.T) / (norms[:, None] * norms)
cosine_df = pd.DataFrame(cosine_sim, index=df["NAMA"], columns=df["NAMA"])

print("\nCosine Similarity (5x5 pertama):")
print(cosine_df.iloc[:5, :5])

# 7. Simpan hasil analisis ke Excel baru
with pd.ExcelWriter("Hasil_Analisis.xlsx") as writer:
    df_clean.to_excel(writer, sheet_name="Skor Mahasiswa", index=False)
    pd.DataFrame(cov_mat).to_excel(writer, sheet_name="Kovarians", index=False)
    pd.DataFrame(corr_mat).to_excel(writer, sheet_name="Korelasi", index=False)
    cosine_df.to_excel(writer, sheet_name="CosineSimilarity")


Empat mahasiswa terbaik berdasarkan skor total:
                               NAMA  Skor_Total
8   RAVEENA AYU DESEMBER SURYOPUTRI        1.30
37                YUNIAR RACHMAWATI        1.30
6             Mohammad Alimun Hakim        1.28
15       SITI NAIA HESTI RACHMAWATI        1.26

Matriks Kovarians:
[[0.01216305 0.01117028 0.01023669 0.0087311 ]
 [0.01117028 0.01677844 0.01489152 0.01255095]
 [0.01023669 0.01489152 0.01905325 0.01447732]
 [0.0087311  0.01255095 0.01447732 0.01547666]]

Matriks Korelasi:
[[1.         0.78192875 0.67244003 0.63636895]
 [0.78192875 1.         0.8328728  0.77886532]
 [0.67244003 0.8328728  1.         0.84307244]
 [0.63636895 0.77886532 0.84307244 1.        ]]

Cosine Similarity (5x5 pertama):
NAMA                     MADINA HEDY ALIFANTI  MARIA DWI KURNIASIH  \
NAMA                                                                 
MADINA HEDY ALIFANTI                 1.000000             0.993687   
MARIA DWI KURNIASIH                  0.993687      